
CREATE TABLE IF NOT EXISTS servers(
 id VARCHAR(100) PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 logo VARCHAR(255) NOT NULL,
 owner_id VARCHAR(100) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS channels(
 id VARCHAR(100) PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 server_id VARCHAR(100) not null,
 channel_type channelType,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_server_id FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE CASCADE ON UPDATE CASCADE
);

create type channelType as enum ('text', 'audio', 'video')
CREATE TABLE IF NOT EXISTS server_members(
 server_id VARCHAR(100) REFERENCES servers(id) ON DELETE CASCADE ON UPDATE CASCADE,
 user_id VARCHAR(100) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
 PRIMARY KEY(server_id, user_id)
);