import './globals.css';

import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';
import localFont from 'next/font/local'

import PulseLoader from '@/components/shared/pulse-loader';
import { Toaster } from '@/components/ui/sonner';
import { SocketProvider } from '@/providers/socket-io';

const ggsans = localFont({
  src: [
    {
      path: '../public/fonts/gg-sans-reg.woff',
      weight: '400',
      style: 'normal'
    },
    {
      path: '/../public/fonts/gg-sans-med.woff',
      weight: '600',
      style: 'normal'
    },
    {
      path: '/../public/fonts/gg-sans-semibold.woff',
      weight: '700',
      style: 'normal'
    },
    {
      path: '/../public/fonts/gg-sans-bold.woff',
      weight: '800',
      style: 'normal'
    }
  ],
  preload: true,
  display: 'swap'
})
export const metadata: Metadata = {
  title: 'ChatFuzion',
  description: 'Generated by create next app',
};


export const viewport: Viewport = {
  colorScheme: 'dark',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,


}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={
            ggsans.className + 'h-full w-full bg-foreground overflow-hidden text-secondary'
          }
        >
          <ClerkLoading>
            <PulseLoader />
          </ClerkLoading>
          <ClerkLoaded>
            <SocketProvider>
              <div className='w-full !overflow-hidden bg-black text-secondary md:bg-foreground'>
                {children}
              </div>
            </SocketProvider>
          </ClerkLoaded>
          <Toaster
            duration={1500}
            className='border-none bg-background !text-white'
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
