import './globals.css';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';

import PulseLoader from '@/components/shared/pulse-loader';
import { Toaster } from '@/components/ui/sonner';
import MessageProviders from '@/providers/message';
import { SocketProvider } from '@/providers/socket-io';

const inter = Inter({ subsets: ['latin'], fallback: ['sans-serif'] });

export const metadata: Metadata = {
  title: 'Discord-clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={
            inter.className +
            'h-full w-full overflow-hidden bg-background text-secondary'
          }
        >
          <ClerkLoading>
            <PulseLoader />
          </ClerkLoading>
          <ClerkLoaded>
            <SocketProvider>
              <MessageProviders>
                <div className='w-full max-w-screen-2xl !overflow-hidden bg-foreground text-secondary'>
                  {children}
                </div>
              </MessageProviders>
            </SocketProvider>
          </ClerkLoaded>
          <Toaster
            duration={1500}
            className='border-none bg-background !text-white'
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
