CREATE TABLE IF NOT EXISTS users(
 id VARCHAR(100) PRIMARY KEY,
 username VARCHAR(255) UNIQUE NOT NULL,
 email VARCHAR(255) UNIQUE NOT NULL,
 image VARCHAR(255) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_relationships(
 follower_id VARCHAR(100) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
 following_id varchar(100) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
 PRIMARY KEY(follower_id, following_id)
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
